#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, sys, unittest, shutil
from pathlib import Path


def main() -> int:
    p=argparse.ArgumentParser()
    p.add_argument('--output', type=Path, default=Path('regression-result.json'))
    p.add_argument('--start-dir', default='tests')
    args=p.parse_args()
    # Keep publication-safety tests reproducible: the test runner must not contaminate
    # the candidate with interpreter-generated bytecode.
    root=Path(__file__).resolve().parents[1]
    for cache in root.rglob('__pycache__'):
        shutil.rmtree(cache, ignore_errors=True)
    for pyc in root.rglob('*.pyc'):
        try: pyc.unlink()
        except FileNotFoundError: pass
    sys.dont_write_bytecode=True
    suite=unittest.defaultTestLoader.discover(args.start_dir)
    result=unittest.TextTestRunner(verbosity=2).run(suite)
    payload={
        'schema':'vertice.regression.v1',
        'tests_run':result.testsRun,
        'failures':len(result.failures),
        'errors':len(result.errors),
        'skipped':len(result.skipped),
        'passed':result.testsRun-len(result.failures)-len(result.errors)-len(result.skipped),
        'status':'PASS' if result.wasSuccessful() else 'FAIL',
    }
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True)+'\n', encoding='utf-8')
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0 if result.wasSuccessful() else 1

if __name__=='__main__':
    raise SystemExit(main())
